version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "MPtest-2025"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build: ./backend
    container_name: mp-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - sqlserver
    volumes:
      - ./backend:/app
      - /app/node_modules

  # frontend:
  #   platform: linux/amd64
  #   build: ./frontend
  #   container_name: mp-frontend
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - ./frontend/.env
  #   depends_on:
  #     - backend

volumes:
  sql_data:
